version: '3'
services:
  couchpotato:
    image: linuxserver/couchpotato:latest
    container_name: couchpotato
    environment:
      TZ: Europe/Paris
    volumes:
      - couchpotato:/config
      - /home/downloads/:/downloads
      - /home/plex/Films/:/movies
    ports :
      - 5050:5050

  ombi:
      image: linuxserver/ombi:latest
      container_name: omby
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ombi:/config
      ports :
        - 3579:3579

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      TZ: Europe/Paris
    volumes:
      - plex:/config
      - /tmp/plex/transcode/:/transcode
      - /home/plex/Films/:/data
    ports :
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

volumes:
  couchpotato:
    driver: local
  ombi:
    driver: local
  plex:
    driver: local